version: "3.8"
services:
  jupyterhub:
    build: .    
    volumes:
    - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    - ./users:/home/jupyterhub
    - ./jupyterhub_data:/srv/jupyterhub
    restart: unless-stopped    
    ports:
      - "8888:8000"
    networks:
      - data-cluster
networks:
  data-cluster:
    external: true